# Generated by Django 3.2.13 on 2022-06-13 12:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField(blank=True)),
                ('music_preview', embed_video.fields.EmbedVideoField(blank=True)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
